# --------------------------- housekeeping -------------------------------------
PEP: config/pep.yaml
#RUN_TYPE: full # full, test

FLYBASE_RELEASE: FB2021_04
GENOME_VERSION: r6.41



# --------------------------- job options --------------------------------------
FASTERQDUMP_MEM: 24000

# Salmon quant (standard quantification approach)
SALMON_VANILLA_LIBTYPE: A 
SALMON_VANILLA_BOOTSTRAPS: 20
SALMON_VANILLA_SEQBIAS: TRUE
SALMON_VANILLA_GCBIAS: TRUE
SALMON_VANILLA_POSBIAS: TRUE
SALMON_VANILLA_USE_AUXTARGETS: TRUE
SALMON_VANILLA_SOFTCLIP: TRUE
SALMON_VANILLA_INCOMPATPRIOR_0: TRUE


# Tximport
# these values will be "counts" for all downstream approaches. This is
# relevant as the input to DESeq2 but also because some normalizations are run
# on these directly. So, that means those normalizations are run on totally raw
# counts if the params below == "no"
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE: scaledTPM # no, scaledTPM, lengthScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TXOUT: dtuScaledTPM # no, scaledTPM, lengthScaledTPM, dtuScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TERMINUS: scaledTPM # no, scaledTPM, lengthScaledTPM


# export of expression to a tab sep matrix. Multiple export units/norms/transforms
# are available. Also possible is normalization to estimated TE copy number,
# which necessarily is performed prior to vst, fpkm, etc, quantile norm, etc.
# 'INCL copy estimation in export' only controls whether this information is generated.
# there will always be two exports for each export type, but if INCL_COPY_ESTIMATION_IN_EXPORT is
# TRUE, the -""
EXPORT_UNITS: ["vst","normcts","fpkm","edaseq_uq","ppc_qn","edaseq_qn"] # ["vst","counts","normcts","fpkm","abundance","cpm","uq","qn"]
INCL_COPY_ESTIMATION_IN_EXPORT: TRUE

# DESeq2 on salmon
DESEQ2_LRT_FORMULA: ~ Strain + sex # not used right now
DESEQ2_LRT_REDUCED_FORMULA: ~ 1 # not used right now
DESEQ2_FITTYPE: local
